---
include:
  - project: packages/gitlab-templates/ci-cd-template-build-docker-images
    ref: master
    file: /templates/docker-build-image.template.yml

stages:
  - build
  - test

variables:
  DOCKER_BUILDKIT: 1

.build-docker:
  stage: build
  extends: .docker-image-build
  variables:
    DOCKER_BUILD_DESTINATION: $CI_REGISTRY_IMAGE:$TAG

.container-security-scan:
  image: registry.gitlab.com/security-products/container-scanning:4
  stage: test
  variables:
    GIT_STRATEGY: none
  allow_failure: true
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json
      dependency_scanning: gl-dependency-scanning-report.json
    paths: [ gl-container-scanning-report.json, gl-dependency-scanning-report.json ]
  script:
    - gtcs scan

build:latest:
  extends: .build-docker
  variables:
    TAG: latest
    DOCKER_BUILDKIT: 1
  only:
    refs:
      - master

build:tags:
  extends: .build-docker
  variables:
    TAG: $CI_COMMIT_TAG
    DOCKER_BUILDKIT: 1
  only:
    refs:
      - tags

security:scan-latest:
  extends: .container-security-scan
  variables:
    DOCKER_IMAGE: $CI_REGISTRY_IMAGE:latest
  only:
    refs:
      - master

security:scan-tags:
  extends: .container-security-scan
  variables:
    DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    refs:
      - tags
