---
include:
  - project: packages/gitlab-templates/ci-cd-template-build-docker-images
    ref: v1.0.0
    file: /templates/docker-build-image.template.yml
  - template: Jobs/Container-Scanning.gitlab-ci.yml

stages:
  - build
  - test

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        DOCKER_BUILD_DESTINATION: ${CI_REGISTRY_IMAGE}:latest
    - if: $CI_COMMIT_TAG != ""
      variables:
        DOCKER_BUILD_DESTINATION: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
    - when: never

variables:
  DOCKER_BUILDKIT: 1

build:
  stage: build
  extends: .docker-image-build

container_scanning:
  variables:
    CS_DEFAULT_BRANCH_IMAGE: ${DOCKER_BUILD_DESTINATION}
