---
- hosts: localhost
  tasks:

    - name: Add Ondrej Sury's apt key (Debian).
      apt_key:
        url: https://packages.sury.org/php/apt.gpg
        state: present

    - name: Add Ondrej Sury's repo (Debian).
      apt_repository:
        repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
        update_cache: yes

    - name: "Install PHP packages"
      package:
        name: 
          - "php7.2-cli"
          - "php7.2-amqp"
          - "php7.2-apcu"
          - "php7.2-bcmath"
          - "php7.2-bz2"
          - "php7.2-calendar"
          - "php7.2-cgi"
          - "php7.2-common"
          - "php7.2-ctype"
          - "php7.2-curl"
          - "php7.2-dba"
          - "php7.2-dev"
          - "php7.2-dom"
          - "php7.2-ds"
          - "php7.2-enchant"
          - "php7.2-exif"
          - "php7.2-fpm"
          - "php7.2-ftp"
          - "php7.2-gd"
          - "php7.2-gettext"
          - "php7.2-gmp"
          - "php7.2-iconv"
          - "php7.2-igbinary"
          - "php7.2-imagick"
          - "php7.2-imap"
          - "php7.2-intl"
          - "php7.2-json"
          - "php7.2-ldap"
          - "php7.2-mbstring"
          - "php7.2-memcached"
          - "php7.2-mongodb"
          - "php7.2-msgpack"
          - "php7.2-mysqli"
          - "php7.2-mysqlnd"
          - "php7.2-odbc"
          - "php7.2-opcache"
          - "php7.2-pdo"
          - "php7.2-pgsql"
          - "php7.2-phar"
          - "php7.2-phpdbg"
          - "php7.2-posix"
          - "php7.2-pspell"
          - "php7.2-psr"
          - "php7.2-readline"
          - "php7.2-redis"
          - "php7.2-shmop"
          - "php7.2-snmp"
          - "php7.2-soap"
          - "php7.2-sockets"
          - "php7.2-sqlite3"
          - "php7.2-sysvmsg"
          - "php7.2-sysvsem"
          - "php7.2-sysvshm"
          - "php7.2-tidy"
          - "php7.2-xdebug"
          - "php7.2-xml"
          - "php7.2-xmlreader"
          - "php7.2-xmlrpc"
          - "php7.2-xsl"
          - "php7.2-zip"
          - "php7.3-cli"
          - "php7.3-amqp"
          - "php7.3-apcu"
          - "php7.3-bcmath"
          - "php7.3-bz2"
          - "php7.3-calendar"
          - "php7.3-cgi"
          - "php7.3-common"
          - "php7.3-ctype"
          - "php7.3-curl"
          - "php7.3-dba"
          - "php7.3-dev"
          - "php7.3-dom"
          - "php7.3-ds"
          - "php7.3-enchant"
          - "php7.3-exif"
          - "php7.3-fpm"
          - "php7.3-ftp"
          - "php7.3-gd"
          - "php7.3-gettext"
          - "php7.3-gmp"
          - "php7.3-iconv"
          - "php7.3-igbinary"
          - "php7.3-imagick"
          - "php7.3-imap"
          - "php7.3-intl"
          - "php7.3-json"
          - "php7.3-ldap"
          - "php7.3-mbstring"
          - "php7.3-memcached"
          - "php7.3-mongodb"
          - "php7.3-msgpack"
          - "php7.3-mysqli"
          - "php7.3-mysqlnd"
          - "php7.3-odbc"
          - "php7.3-opcache"
          - "php7.3-pdo"
          - "php7.3-pgsql"
          - "php7.3-phar"
          - "php7.3-phpdbg"
          - "php7.3-posix"
          - "php7.3-pspell"
          - "php7.3-psr"
          - "php7.3-readline"
          - "php7.3-redis"
          - "php7.3-shmop"
          - "php7.3-snmp"
          - "php7.3-soap"
          - "php7.3-sockets"
          - "php7.3-sqlite3"
          - "php7.3-sysvmsg"
          - "php7.3-sysvsem"
          - "php7.3-sysvshm"
          - "php7.3-tidy"
          - "php7.3-xdebug"
          - "php7.3-xml"
          - "php7.3-xmlreader"
          - "php7.3-xmlrpc"
          - "php7.3-xsl"
          - "php7.3-zip"
          - "php7.4-cli"
          - "php7.4-amqp"
          - "php7.4-apcu"
          - "php7.4-bcmath"
          - "php7.4-bz2"
          - "php7.4-calendar"
          - "php7.4-cgi"
          - "php7.4-common"
          - "php7.4-ctype"
          - "php7.4-curl"
          - "php7.4-dba"
          - "php7.4-dev"
          - "php7.4-dom"
          - "php7.4-ds"
          - "php7.4-enchant"
          - "php7.4-exif"
          - "php7.4-fpm"
          - "php7.4-ftp"
          - "php7.4-gd"
          - "php7.4-gettext"
          - "php7.4-gmp"
          - "php7.4-iconv"
          - "php7.4-igbinary"
          - "php7.4-imagick"
          - "php7.4-imap"
          - "php7.4-intl"
          - "php7.4-json"
          - "php7.4-ldap"
          - "php7.4-mbstring"
          - "php7.4-memcached"
          - "php7.4-mongodb"
          - "php7.4-msgpack"
          - "php7.4-mysqli"
          - "php7.4-mysqlnd"
          - "php7.4-odbc"
          - "php7.4-opcache"
          - "php7.4-pdo"
          - "php7.4-pgsql"
          - "php7.4-phar"
          - "php7.4-phpdbg"
          - "php7.4-posix"
          - "php7.4-pspell"
          - "php7.4-psr"
          - "php7.4-readline"
          - "php7.4-redis"
          - "php7.4-shmop"
          - "php7.4-snmp"
          - "php7.4-soap"
          - "php7.4-sockets"
          - "php7.4-sqlite3"
          - "php7.4-sysvmsg"
          - "php7.4-sysvsem"
          - "php7.4-sysvshm"
          - "php7.4-tidy"
          - "php7.4-xdebug"
          - "php7.4-xml"
          - "php7.4-xmlreader"
          - "php7.4-xmlrpc"
          - "php7.4-xsl"
          - "php7.4-zip"
          - "php8.0-cli"
          - "php8.0-opcache"
          - "php8.0-bcmath"
          - "php8.0-bz2"
          - "php8.0-cli"
          - "php8.0-common"
          - "php8.0-curl"
          - "php8.0-gd"
          - "php8.0-gmp"
          - "php8.0-intl"
          - "php8.0-mbstring"
          - "php8.0-pgsql"
          - "php8.0-sqlite3"
          - "php8.0-readline"
          - "php8.0-xml"
          - "php8.0-zip"
          - "php8.0-soap"
          - "php8.0-ldap"
          - "php8.0-mysql"
          - "php8.0-mysqli"
          - "php8.0-redis"
          - "php8.0-amqp"
          - "php8.0-imagick"
          - "php8.0-xdebug"
          - "php8.1-cli"
          - "php8.1-opcache"
          - "php8.1-bcmath"
          - "php8.1-bz2"
          - "php8.1-cli"
          - "php8.1-common"
          - "php8.1-curl"
          - "php8.1-gd"
          - "php8.1-gmp"
          - "php8.1-intl"
          - "php8.1-mbstring"
          - "php8.1-pgsql"
          - "php8.1-sqlite3"
          - "php8.1-readline"
          - "php8.1-xml"
          - "php8.1-zip"
          - "php8.1-soap"
          - "php8.1-ldap"
          - "php8.1-mysql"
          - "php8.1-mysqli"
          - "php8.1-redis"
          - "php8.1-amqp"
          - "php8.1-imagick"
          - "php8.1-xdebug"
          - "php8.2-cli"
          - "php8.2-opcache"
          - "php8.2-bcmath"
          - "php8.2-bz2"
          - "php8.2-cli"
          - "php8.2-common"
          - "php8.2-curl"
          - "php8.2-gd"
          - "php8.2-gmp"
          - "php8.2-intl"
          - "php8.2-mbstring"
          - "php8.2-pgsql"
          - "php8.2-sqlite3"
          - "php8.2-readline"
          - "php8.2-xml"
          - "php8.2-zip"
          - "php8.2-soap"
          - "php8.2-ldap"
          - "php8.2-mysql"
          - "php8.2-mysqli"
          - "php8.2-redis"
          - "php8.2-amqp"
          - "php8.2-imagick"
          - "php8.2-xdebug"

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: Clear cache
      command: apt-get clean all

    - name: Install composer in version 1
      get_url:
        url: https://getcomposer.org/composer.phar
        dest: /usr/local/bin/composer-legacy
        mode: "0755"

    - name: Install composer in version 2
      get_url:
        url: https://getcomposer.org/composer.phar
        dest: /usr/local/bin/composer
        mode: "0755"

    - name: Link composer for backwards compatibility
      file:
        state: link
        path: /usr/local/bin/composer2
        src: /usr/local/bin/composer

    - name: "Update composer"
      command: "composer self-update --2"

    - name: "Update composer"
      command: "composer-legacy self-update --1"
