---
- hosts: localhost
  tasks:
    - name: Add Ondrej Sury's apt key (Debian).
      apt_key:
        url: https://packages.sury.org/php/apt.gpg
        state: present

    - name: Add Ondrej Sury's repo (Debian).
      apt_repository:
        repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
        update_cache: yes

    - name: "Install PHP packages"
      package:
        name:
          - "php8.2-cli"
          - "php8.2-opcache"
          - "php8.2-bcmath"
          - "php8.2-bz2"
          - "php8.2-cli"
          - "php8.2-common"
          - "php8.2-curl"
          - "php8.2-gd"
          - "php8.2-gmp"
          - "php8.2-intl"
          - "php8.2-mbstring"
          - "php8.2-pgsql"
          - "php8.2-sqlite3"
          - "php8.2-readline"
          - "php8.2-xml"
          - "php8.2-zip"
          - "php8.2-soap"
          - "php8.2-ldap"
          - "php8.2-mysql"
          - "php8.2-mysqli"
          - "php8.2-redis"
          - "php8.2-amqp"
          - "php8.2-imagick"
          - "php8.2-xdebug"

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: Clear cache
      command: apt-get clean all
